name: CI/CD Pipeline

on:  
  # regra pull_request apenas para a branch main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # job para construir o projeto
  build:
    runs-on: ubuntu-latest
    steps:
      # Ação para clonar o repositório
      - name: Check out the repository
        uses: actions/checkout@main

      # Ação para configurar o JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ação para armazenar em cache as dependências do Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Ação para construir o projeto com Maven
      - name: Build with Maven
        run: mvn clean install

  # job para testar o projeto
  test:
    runs-on: ubuntu-latest
    needs: build  # Garante que o job 'build' seja executado com sucesso antes do 'test'
    steps:
      # Ação para clonar o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Ação para configurar o JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Ação para executar o Checkstyle
      - name: Run checkstyle
        run: mvn checkstyle:check

      # Ação para executar os testes com Maven
      - name: Run tests with Maven
        run: mvn clean test
        
      # Ação para gerar o relatório de testes
      #- name: Generate Test Report
      #  run: mvn surefire-report:report -DoutputDirectory=target/surefire-reports/

      # Ação para armazenar os resultados dos testes
      

      # TODO list surefire report files
      #- name: List Surefire Report files
      #  run: ls -alh target/surefire-reports/
      
      # Ação para obter os resultados dos testes
      # - name: Get test results
        # run: |
        #   # Extract the number of tests from the surefire report
        #   passed_tests=$(grep -oP '(?<=Tests run: )\d+(?=, Failures: 0, Errors: 0, Skipped: 0)' target/surefire-reports/*.txt | awk '{sum+=$1} END {print sum}')
        #   total_tests=$(grep -oP '(?<=Tests run: )\d+' target/surefire-reports/*.txt | awk '{sum+=$1} END {print sum}')
        #   if [ -z "$passed_tests" ]; then
        #     passed_tests=0
        #   fi
        #   if [ -z "$total_tests" ]; then
        #     total_tests=0
        #   fi
        #   echo "Passed $passed_tests / $total_tests tests"
      
      # Ação para gerar o relatório de cobertura de código
      - name: Generate Code Coverage Report
        run: mvn jacoco:report -DoutputDirectory=target/jacoco-report/
      
      - name: Archive Test Results
        uses: actions/upload-artifact@main
        with:
          name: test-results
          path: target/jacoco-report/
          if-no-files-found: warn
      
      # TODO configurar execução do SonarCloud plugin
      # - name: Analyze Code with SonarCloud
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Usa o token do GitHub Secrets
      #     run: mvn sonar:sonar -Dsonar.projectKey=rfanti_hello-world-example -Dsonar.organization=rfanti -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  # job para empacotar o projeto
  package:
    runs-on: ubuntu-latest
    needs: test  # Garante que o job 'test' seja executado com sucesso antes do 'package'
    steps:
      # Ação para clonar o repositório
      - name: Checkout code
        uses: actions/checkout@main

      # Ação para configurar o JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ação para empacotar o projeto com Maven
      - name: Package JAR
        run: mvn package

      # Ação para armazenar o artefato JAR
      - name: Upload JAR artifact
        uses: actions/upload-artifact@main
        with:
          name: hello-world-grupo4
          path: target/*.jar

  # job para realizar o deploy do projeto
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      # Ação para Deploy do projeto em ambiente Develop
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to Staging Environment..."
          # scp -i ~/.ssh/id_rsa target/*.jar user@staging-server:/opt/app
          # ssh -i ~/.ssh/id_rsa user@staging-server "sudo systemctl restart app"

      # Ação para Deploy do projeto em ambiente Production 
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Production Environment..."
          # scp -i ~/.ssh/id_rsa target/*.jar user@production-server:/opt/app
          # ssh -i ~/.ssh/id_rsa user@production-server "sudo systemctl restart app"
